name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install AWS CLI
      run: sudo apt-get install awscli

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AKIAZ24ISV46JUHQMH5E }}
        aws-secret-access-key: ${{ secrets.IoE5AwcGzjHkACrUSXnli+LVDO/bGbmm8+5bv5/0 }}
        aws-region: us-east-1  # Update with your AWS region

    - name: Deploy to S3
      run: |
        aws s3 sync . s3://cloudresumechallengebp --exclude ".git/*" --delete
